export const GET_APARTMENTS = 'GET_APARTMENTS';
export const ADD_APARTMENT = 'ADD_APARTMENT';
export const UPDATE_APARTMENT = 'UPDATE_APARTMENT';
export const DELETE_APARTMENT = 'DELETE_APARTMENT';
export const DELETE_FACTURE = 'DELETE_FACTURE';
export const PAY_APARTMENT = 'PAY_APARTMENT';
export const SELECT_APARTMENT = 'SELECT_APARTMENT';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const CLEAR_SELECTEDAPARTMENT = 'CLEAR_SELECTEDAPARTMENT';
export const GET_ADMIN = 'GET_ADMIN';




